# This integration test ci job is used to test the DB alterations compatibility with the current codebase.

name: Alteration Compatibility Test

on:
  push:
    branches:
      - master
      - "push-action/**"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout head
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ./head

      # compare the current codebase with HEAD and check if there are any changes in the alterations folder
      - name: Check for alteration changes
        id: check-alteration-changes
        working-directory: ./head
        run: |
          CHANGE_FILES=$(git diff --name-only HEAD...origin/${{ github.base_ref }} | grep -q 'packages/schemas/alterations/*')
          if [ -z "$CHANGE_FILES" ]; then
            echo "No alteration changes detected"
            exit 0
          else
            echo "Alteration changes detected"
            echo "$CHANGE_FILES"
          fi

      - name: Copy lockfile # Make setup workflow happy
        run: cp ./head/pnpm-lock.yaml ./

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v3
        with:
          run-install: false

      #prepack the alteration cli
      - name: prepack
        working-directory: ./head
        run: |
          npm i
          npm run prepack
