name: Bump Logto submodule HEAD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump cloud Logto submodule HEAD
        uses: ./.github/actions/create-submodule-bump-pr
        with:
          github_token: ${{ secrets.BOT_PAT }}
          checkout_branch: "master"
          pr_against_branch: "master"
          parent_repository: "https://github.com/logto-io/cloud"
          branch_name: "bump-cloud-logto-submodule"
