name: Core

on:
  push:
    branches: [ master ]
    paths: [ 'packages/core/**', 'packages/phrases/**', 'packages/schemas/**' ]
  pull_request:
    branches: [ master ]
    paths: [ 'packages/core/**', 'packages/phrases/**', 'packages/schemas/**' ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - name: Lint
        working-directory: packages/core
        run: pnpm lint

      - name: Build
        working-directory: packages/core
        run: pnpm build
