name: Dockerize

on:
  push:
    branches: [master]

concurrency:
  group: dockerize-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dockerize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: logto
          outputs: type=docker,dest=/tmp/logto.tar
      
      - name: Load image
        run: docker load -i /tmp/logto.tar
      
      - name: Compose up
        run: docker compose up -d

      - name: Sleep for 30 seconds
        run: sleep 30s
      
      - name: Health check
        run: curl http://localhost:3001/api/status -If

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: logto.${{ github.sha }}
          path: /tmp/logto.tar
