name: Main

on:
  push:
    branches: [master]
  pull_request:

jobs:
  main-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and pnpm
        uses: logto-io/actions-node-pnpm-run-steps@v1.2.2

      - name: Build
        run: pnpm ci:build

  main-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and pnpm
        uses: logto-io/actions-node-pnpm-run-steps@v1.2.2

      - name: Prepack
        run: pnpm prepack

      - name: Lint
        run: pnpm ci:lint

      - name: Stylelint
        run: pnpm ci:stylelint

  main-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and pnpm
        uses: logto-io/actions-node-pnpm-run-steps@v1.2.2

      - name: Prepack
        run: pnpm prepack

      - name: Test
        run: pnpm ci:test

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: core
          directory: ./packages/core
