name: Main

on:
  push:
    branches: [ master ]
    paths: [ 'packages/**', 'packages/**' ]
  pull_request:
    branches: [ master ]
    paths: [ 'packages/**', 'packages/**' ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node and pnpm
        uses: logto-io/actions-node-pnpm-run-steps@v1.0.2

      - name: Lint
        run: pnpm -- lerna run --stream lint

      - name: Build
        run: pnpm -- lerna run --stream build

      - name: Test
        run: pnpm -- lerna run --stream test
