name: Main

on:
  push:
    branches:
      - master
      - 'push-action/**'
  pull_request:

concurrency:
  group: main-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v2

      - name: Build
        run: pnpm ci:build

  main-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v2

      - name: Prepack
        run: pnpm prepack

      - name: Lint
        run: pnpm ci:lint

      - name: Stylelint
        run: pnpm ci:stylelint

  main-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v2

      - name: Build for test
        run: pnpm -r build:test

      - name: Test
        run: pnpm ci:test

      - name: Codecov core
        uses: codecov/codecov-action@v3
        with:
          flags: core
          directory: ./packages/core

      - name: Codecov ui
        uses: codecov/codecov-action@v3
        with:
          flags: ui
          directory: ./packages/ui

  main-dockerize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
  
  main-alteration-sequence:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v2

      - name: Build
        run: pnpm prepack
      
      - name: Check alteration sequence
        run: node .scripts/check-alterations-sequence.js
