name: Main

on:
  push:
    branches: [master]
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and pnpm
        uses: logto-io/actions-node-pnpm-run-steps@v1.2.1

      - name: Build
        run: pnpm ci:build

      - name: Lint
        run: pnpm ci:lint

      - name: Stylelint
        run: pnpm ci:stylelint

      - name: Test
        run: pnpm ci:test

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: core
          directory: ./packages/core
