name: UI

on:
  push:
    branches: [ master ]
    paths: [ 'packages/ui/**' ]
  pull_request:
    branches: [ master ]
    paths: [ 'packages/ui/**' ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - name: Lint
        working-directory: packages/ui
        run: pnpm lint && pnpm stylelint

      - name: Test
        working-directory: packages/ui
        run: pnpm test

      - name: Build
        working-directory: packages/ui
        run: pnpm build
