name: Update Metadata

on:
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: silverhand-io/actions-add-labels-run-steps@v1.1.2
        with:
          title: ${{ github.event.pull_request.title || github.event.issue.title }}
          github-token: ${{ github.token }}

      - name: Add assignees
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ github.token }}
          assignees: ${{ github.actor }}

  pr-size-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Calc Size Diff
        run: |
          curl -fsSLO https://gist.githubusercontent.com/gao-sun/88dac6c38e86f4ae12c8a7c3e777040a/raw/28bee6843989937c9fd24bd293227436f5981a4a/git-file-size-diff.sh
          ./git-file-size-diff.sh --cached master
